services:
  - type: web
    name: webhook-api
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false

  - type: worker
    name: webhook-worker
    env: docker
    plan: free
    buildCommand: ""
    startCommand: "rq worker -u $REDIS_URL default"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
